const link = @import("../../link.zig");

const Mir = @import("Mir.zig");
const Self = @This();

pub fn emit(self: Self, mir: []Mir.Insn, bin_file: *link.File) void {
    _ = bin_file; // autofix
    for (mir) |insn| switch (insn.tag) {
        .SEC,
        .CLC,
        .SEN,
        .CLN,
        .SEZ,
        .CLZ,
        .SEI,
        .CLI,
        .SES,
        .CLS,
        .SEV,
        .CLV,
        .SET,
        .CLT,
        .SEH,
        .CLH,
        .BREAK,
        .NOP,
        .SLEEP,
        .WDR,
        => unreachable, //none
        .ADD,
        .ADC,
        .SUB,
        .SBC,
        .AND,
        .OR,
        .EOR,
        .MUL,
        .MULS,
        .MULSU,
        .FMUL,
        .FMULS,
        .FMULSU,
        .MOV,
        .MOVW,
        => unreachable, // rr
        .ADIW,
        .SUBI,
        .SBCI,
        .SBIW,
        .ANDI,
        .ORI,
        .SBR,
        .CBR,
        => unreachable, //r_k
        .COM,
        .NEG,
        .INC,
        .DEC,
        .TST,
        .CLR,
        .SER,
        .LSL,
        .LSR,
        .ROL,
        .ROR,
        .ASR,
        .SWAP,
        => unreachable, // r
        .DES,
        => unreachable, // des
        .BREQ,
        .BRNE,
        .BRCS,
        .BRCC,
        .BRSH,
        .BRLO,
        .BRMI,
        .BRPL,
        .BRGE,
        .BRLT,
        .BRHS,
        .BRHC,
        .BRTS,
        .BRTC,
        .BRVS,
        .BRVC,
        .BRIE,
        .BRID,
        => unreachable, // k
        .RJMP,
        .IJMP,
        .EIJMP,
        .JMP,
        .RCALL,
        .ICALL,
        .EICALL,
        .CALL,
        .RET,
        .RETI,
        .CPSE,
        .CP,
        .CPC,
        .CPI,
        .SBRC,
        .SBRS,
        .SBIC,
        .SBIS,
        .BRBS,
        .BRBC,
        .LDI,
        .LDS,
        .LD,
        .LDD,
        .STS,
        .ST,
        .STD,
        .LPM,
        .ELPM,
        .SPM,
        .IN,
        .OUT,
        .PUSH,
        .POP,
        .XCH,
        .LAS,
        .LAC,
        .LAT,
        .SBI,
        .CBI,
        .BST,
        .BLD,
        .BSET,
        .BCLR,
        => unreachable,
    };
    _ = self; // autofix
}
